# Generated by Django 3.2 on 2022-09-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20220909_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand_products'),
        ),
    ]
