# Generated by Django 3.2 on 2022-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brands_brand_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.AddField(
            model_name='brand_products',
            name='brand_name',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
