# Generated by Django 3.2 on 2022-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20220909_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_products',
            name='brand_name',
            field=models.CharField(default=False, max_length=254, null=True),
        ),
    ]
