# Generated by Django 3.2 on 2022-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_brand_products_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_products',
            name='brand_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
