# Generated by Django 3.2 on 2022-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brand_products_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='brand_products',
        ),
        migrations.AddField(
            model_name='brand_products',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brands'),
        ),
    ]
