# Generated by Django 3.2 on 2022-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_rename_product_name_brand_products_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_products',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='brand_products',
            name='max_quant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
