# Generated by Django 3.2 on 2022-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20221103_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_products',
            name='max_quant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
