# Generated by Django 3.2 on 2022-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_alter_brand_products_max_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_email',
            field=models.EmailField(default='Email', max_length=254),
        ),
    ]
