# Generated by Django 3.2 on 2022-11-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20221119_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Newsletter',
        ),
    ]
