# Generated by Django 3.2 on 2022-11-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
