# Generated by Django 3.2 on 2022-11-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_subscribedusers_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
