# Generated by Django 3.2 on 2022-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Why', models.CharField(max_length=9999)),
                ('How', models.CharField(max_length=9999)),
            ],
        ),
    ]
