# Generated by Django 3.2 on 2022-11-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='How',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='mission',
            name='Why',
            field=models.TextField(max_length=9999),
        ),
    ]
